### ISSUE TITLE
反省点の洗い出し

### ISSUE THREAD

**Issue by fujiwara402** [RICHMEDIA-MILLIONTH2014-B/LINE_Diet_Manager#1]
今後の方針を決めるためにみんなで振り返りしましょう。
今回のこの企画にとどまらず、それぞれがこれからハッカソンやインターンでも活かせるような反省の仕方ができるといいね。

**Comment by fujiwara402** [comment]
反省点
1.今回の企画をするにあたって、問題提起から始めていたが、LINEビジネスコネクトの特性から考えると、対象とする企業をもっと考える必要があったと思う。 特定の分野の企業とその分野にある問題点をセットにすると考えやすかったのかな、と思います。この企画の"解像度の低さ"もこの辺に起因するものがあるかと。

2.LINEでなければいけない要素が明確でなかった。これは最終プレゼンのときに突っ込まれたけど、あとから考えてみるとユーザが使い慣れたインターフェイスで付加価値を生み出せる、とか後出しでもなんとかなったのかなとは思います。予想できた質問だけにちょっと悔しい。

3.類似サービスの調査と比較ができていなかった。ハッカソンだから時間がなくてどこかおろそかになってしまうのは仕方ないのかなと思うけど、サービスの新規企画には基本となりそうな部分なので、これからは抑えておきたい。

**Comment by mziyut** [comment]
懐かしい

**Comment by fujiwara402** [comment]
それな
